/**
 * Prism.js language definition for zenv
 * zEnv.*.zolo - Environment configuration files
 *
 * Extends base 'zolo' language with file-type-specific patterns.
 *
 * Generated by zlsp/zlsp/generators/generate_prism_zolo.py
 * DO NOT EDIT MANUALLY - regenerate with: python3 -m zlsp.generators.generate_prism_zolo
 */

Prism.languages.zenv = Prism.languages.extend('zolo', {
    'zenv-config-root': {
        pattern: /((?:^|\n)[ \t]*)(?:LOG_LEVEL|DEBUG|DEPLOYMENT)(?=\s*:)/m,
        alias: 'keyword',
        lookbehind: true,
    },
    'zenv-z-uppercase-root': {
        pattern: /((?:^|\n)[ \t]*)Z[A-Z0-9_]+(?=\s*:)/m,
        alias: 'function',
        lookbehind: true,
    },
    'root-key': {
        pattern: /(^|\n)([A-Z][a-zA-Z0-9_]*)(?=\s*(?:\([^)]+\))?[*!^~]?:)/m,
        alias: 'class-name',
        lookbehind: true,
    },
    'znavbar-nested': {
        pattern: /(?<=\n)[ \t]{1}[a-zA-Z][a-zA-Z0-9_]*(?=\s*:)/m,
        alias: 'type',
        lookbehind: true,
    },
    'zsub-key': {
        pattern: /(?<=\n)[ \t]{2,}zSub(?=\s*:)/m,
        alias: 'keyword',
        lookbehind: true,
    },
    'zrbac-key': {
        pattern: /\bzRBAC(?=\s*:)/,
        alias: 'constant',
    },
    'property': {
        pattern: /\b[a-zA-Z][a-zA-Z0-9_]*(?=\s*(?:\([^)]+\))?[*!]?:)/,
    },
    'prefix-modifier': {
        pattern: /[\^~](?=[a-zA-Z][a-zA-Z0-9_]*\s*:)/,
        alias: 'variable',
    },
    'suffix-modifier': {
        pattern: /[*!](?=:)/,
        alias: 'operator',
    }
});

// Insert value patterns BEFORE string-unquoted for priority
Prism.languages.insertBefore('zenv', 'string-unquoted', {
        'zpath-value': {
            pattern: /[@~]\.[a-zA-Z0-9_./]+/,
            alias: 'string',
        }
});
Prism.languages.insertBefore('zenv', 'string-unquoted', {
        'env-constant-value': {
            pattern: /\b(?:DEBUG|PROD|INFO|WARNING|ERROR|CRITICAL|SESSION|Development|Production)\b/,
            alias: 'number',
        }
});

// Support both ```zenv and ```zEnv code fences
Prism.languages.zEnv = Prism.languages.zenv;
