/**
 * Prism.js language definition for zconfig
 * zConfig.*.zolo - System configuration files
 *
 * Extends base 'zolo' language with file-type-specific patterns.
 *
 * Generated by zlsp/zlsp/generators/generate_prism_zolo.py
 * DO NOT EDIT MANUALLY - regenerate with: python3 -m zlsp.generators.generate_prism_zolo
 */

Prism.languages.zconfig = Prism.languages.extend('zolo', {
    'zconfig-special-root': {
        pattern: /((?:^|\n)[ \t]*)(?:zMachine|Z[A-Z0-9_]+)(?=\s*:)/m,
        alias: 'function',
        lookbehind: true,
    },
    'root-key': {
        pattern: /(^|\n)([A-Z][a-zA-Z0-9_]*)(?=\s*(?:\([^)]+\))?[*!^~]?:)/m,
        alias: 'class-name',
        lookbehind: true,
    },
    'zmachine-locked-section': {
        pattern: /(?<=\n)[ \t]{1}(?:storage|python_runtime|launch_commands|network|display|memory|machine_identity|user_paths|gpu|cpu)(?=\s*:)/m,
        alias: 'constant',
        lookbehind: true,
    },
    'zmachine-editable-section': {
        pattern: /(?<=\n)[ \t]{1}(?:user_preferences|time_date_formatting|custom)(?=\s*:)/m,
        alias: 'variable',
        lookbehind: true,
    },
    'zconfig-property': {
        pattern: /(?<=\n)[ \t]{2,}[a-zA-Z][a-zA-Z0-9_]*(?=\s*:)/m,
        alias: 'variable',
        lookbehind: true,
    },
    'property': null
});

// Support both ```zconfig and ```zConfig code fences
Prism.languages.zConfig = Prism.languages.zconfig;
