/**
 * Prism.js language definition for zui
 * zUI.*.zolo - User interface component files
 *
 * Extends base 'zolo' language with file-type-specific patterns.
 *
 * Generated by zlsp/zlsp/generators/generate_prism_zolo.py
 * DO NOT EDIT MANUALLY - regenerate with: python3 -m zlsp.generators.generate_prism_zolo
 */

Prism.languages.zui = Prism.languages.extend('zolo', {
    'zui-special-root': {
        pattern: /((?:^|\n)[ \t]*)(?:zMeta|zVaF)(?=\s*:)/m,
        alias: 'function',
        lookbehind: true,
    },
    'root-key': {
        pattern: /(^|\n)([a-zA-Z][a-zA-Z0-9_]*)(?=\s*(?:\([^)]+\))?[*!^~]?:)/m,
        alias: 'class-name',
        lookbehind: true,
    },
    'property': {
        pattern: /\b[a-zA-Z][a-zA-Z0-9_]*(?=\s*(?:\([^)]+\))?[*!]?:)/,
    },
    'prefix-modifier': {
        pattern: /[\^~](?=[a-zA-Z][a-zA-Z0-9_]*\s*:)/,
        alias: 'variable',
    },
    'suffix-modifier': {
        pattern: /[*!](?=:)/,
        alias: 'operator',
    }
});

// Insert key patterns BEFORE 'property' for correct priority
Prism.languages.insertBefore('zui', 'property', {
        'zrbac-key': {
            pattern: /\bzRBAC(?=\s*:)/,
            alias: 'constant',
        },
        'control-flow-key': {
            pattern: /\bzWizard(?=\s*:)/,
            alias: 'function',
        },
        'zsub-key': {
            pattern: /\bzSub(?=\s*:)/,
            alias: 'keyword',
        },
        'zui-element': {
            pattern: /\b(?:zFunc|zTerminal|zInfo|zInput|zSuccess|zDL|zRange|zCrumbs|zH3|zNavBar|zH2|zUL|zURL|zH0|zCode|zText|zBtn|zH6|zCheckbox|zError|zH5|zTable|zH1|zLink|zWizard|zMD|zImage|zSelect|zSignal|zWarning|zOL|zH4)(?=\s*(?:\([^)]+\))?[*!]?:)/,
            alias: 'function',
        },
        'metadata': {
            pattern: /\b_z[A-Z][a-zA-Z]+(?=:)/,
            alias: 'keyword',
        },
        'zui-element-property': {
            pattern: /\b(?:action|alt_text|autocomplete|break_message|caption|checked|color|columns|content|disabled|format|href|id|indent|interactive|items|label|limit|max|maxlength|min|minlength|multi|multiple|name|offset|open_prompt|options|parent|pattern|pause|placeholder|prefix|prompt|readonly|rel|required|rows|semantic|show|show_header|size|src|step|style|suffix|target|title|type|value|window|zAnchor)(?=\s*(?:\([^)]+\))?:)/,
            alias: 'variable',
        },
        'zdispatch-event': {
            pattern: /\b(?:zCRUD|zData|zDialog|zDispatch|zLogin|zMenu)(?=\s*(?:\([^)]+\))?[*!]?:)/,
            alias: 'dispatch-event',
        }
});

// Support both ```zui and ```zUI code fences
Prism.languages.zUI = Prism.languages.zui;
