/**
 * Prism.js language definition for zspark
 * zSpark.*.zolo - Application entry point configuration
 *
 * Extends base 'zolo' language with file-type-specific patterns.
 *
 * Generated by zlsp/zlsp/generators/generate_prism_zolo.py
 * DO NOT EDIT MANUALLY - regenerate with: python3 -m zlsp.generators.generate_prism_zolo
 */

Prism.languages.zspark = Prism.languages.extend('zolo', {
});

// Insert value patterns BEFORE string-unquoted for priority
Prism.languages.insertBefore('zspark', 'string-unquoted', {
        'zspark-zpath-value': {
            pattern: /(?<=(?:zScrapath|zVaFolder|zSpace):\s*)[@~](?:\.[a-zA-Z0-9_./]+)?/,
            alias: 'keyword',
            lookbehind: true,
            greedy: true,
        }
});

// Support both ```zspark and ```zSpark code fences
Prism.languages.zSpark = Prism.languages.zspark;
