/**
 * Prism.js language definition for zschema
 * zSchema.*.zolo - Data schema definition files
 *
 * Extends base 'zolo' language with file-type-specific patterns.
 *
 * Generated by zlsp/zlsp/generators/generate_prism_zolo.py
 * DO NOT EDIT MANUALLY - regenerate with: python3 -m zlsp.generators.generate_prism_zolo
 */

Prism.languages.zschema = Prism.languages.extend('zolo', {
    'zschema-zmeta-root': {
        pattern: /((?:^|\n)[ \t]*)zMeta(?=\s*:)/m,
        alias: 'function',
        lookbehind: true,
    },
    'root-key': {
        pattern: /((?:^|\n)[ \t]*)[A-Z][a-zA-Z0-9_]*(?=\s*(?:\([^)]+\))?[*!^~]?:)/m,
        alias: 'class-name',
        lookbehind: true,
    },
    'zschema-zos-data': {
        pattern: /(?<=\n)[ \t]{1}(?:Data_Type|Data_Label|zMigrationVersion|Data_Source|zMigration|Schema_Name)(?=\s*:)/m,
        alias: 'keyword',
        lookbehind: true,
    },
    'zschema-property': {
        pattern: /(?<=\n)[ \t]{2,}(?:unique|type|min|default|auto_increment|comment|min_length|zHash|required|pk|format|pattern|rules|max|max_length)(?=\s*:)/m,
        alias: 'keyword',
        lookbehind: true,
    },
    'property': {
        pattern: /\b[a-zA-Z][a-zA-Z0-9_]*(?=\s*(?:\([^)]+\))?[*!]?:)/,
    }
});

// Support both ```zschema and ```zSchema code fences
Prism.languages.zSchema = Prism.languages.zschema;
