/**
 * Prism.js base language definition for zolo
 * Generic .zolo syntax - string-first philosophy
 *
 * This is the foundation for all specialized zolo languages.
 * Other languages extend this base with file-type-specific patterns.
 *
 * Generated by zlsp/zlsp/generators/generate_prism_zolo.py
 * DO NOT EDIT MANUALLY - regenerate with: python3 -m zlsp.generators.generate_prism_zolo
 */

Prism.languages.zolo = {
    'comment': {
        pattern: /(^[ \t]*#(?!>).*|#>[\s\S]*?<#)/m,
        alias: 'comment',
        greedy: true,
    },
    'root-key': {
        pattern: /(^|\n)([a-zA-Z][a-zA-Z0-9_]*)(?=\s*(?:\([^)]+\))?[*!^~]?:)/m,
        alias: 'class-name',
        lookbehind: true,
    },
    'property': {
        pattern: /(?<=\n)[ \t]+[a-zA-Z][a-zA-Z0-9_]*(?=\s*(?:\([^)]+\))?[*!]?:)/m,
        lookbehind: true,
    },
    'type-hint': {
        pattern: /\([^)]+\)(?=\s*:)/,
        inside: {
            'type-hint-paren': {
                pattern: /[()]/,
                alias: 'punctuation',
            },
            'type-hint-text': {
                pattern: /[^()]+/,
                alias: 'type',
            }
        },
    },
    'dash-list': {
        pattern: /(?<=\n)[ \t]*-(?:\s+[^\n]+)?/,
        alias: 'language-zolo',
        lookbehind: true,
        inside: {
            'dash': {
                pattern: /^[ \t]*-\s*/,
                alias: 'bracket',
            },
            'object': {
                pattern: /\{(?:[^{}]|\{[^{}]*\})*\}/,
                alias: 'language-zolo',
                greedy: true,
                inside: {
                    'brace': {
                        pattern: /[{}]/,
                        alias: 'brace',
                    },
                    'comma': {
                        pattern: /,/,
                        alias: 'punctuation',
                    },
                    'property': {
                        pattern: /[a-zA-Z][a-zA-Z0-9_]*(?=\s*:)/,
                        alias: 'property',
                    },
                    'colon': {
                        pattern: /:/,
                        alias: 'punctuation',
                    },
                    'array': {
                        pattern: /\[(?:[^\[\]]|\[(?:[^\[\]]|\[(?:[^\[\]]|\[[^\[\]]*\])*\])*\])*\]/,
                        alias: 'language-zolo',
                        greedy: true,
                        inside: {
                            'bracket': {
                                pattern: /[\[\]]/,
                                alias: 'bracket',
                            },
                            'comma': {
                                pattern: /,/,
                                alias: 'punctuation',
                            },
                            'string': {
                                pattern: /[^\[\],\s]+(?:\s+[^\[\],\s]+)*/,
                                alias: 'string',
                            }
                        },
                    },
                    'boolean': {
                        pattern: /\b(?:true|false|True|False)\b/,
                        alias: 'boolean',
                    },
                    'null': {
                        pattern: /\bnull\b/,
                        alias: 'null',
                    },
                    'number': {
                        pattern: /(?<![a-zA-Z0-9_])-?(?:0(?!\d)|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?(?![a-zA-Z0-9_])/,
                        alias: 'number',
                    },
                    'string': {
                        pattern: /[^{}\[\],:\s]+(?:\s+[^{}\[\],:\s]+)*/,
                        alias: 'string',
                    }
                },
            },
            'array': {
                pattern: /\[[^\[\]]*(?:\[[^\[\]]*\][^\[\]]*)*\]/,
                alias: 'language-zolo',
                inside: {
                    'bracket': {
                        pattern: /[\[\]]/,
                        alias: 'bracket',
                    },
                    'comma': {
                        pattern: /,/,
                        alias: 'punctuation',
                    },
                    'string': {
                        pattern: /[^\[\],\s]+(?:\s+[^\[\],\s]+)*/,
                        alias: 'string',
                    }
                },
            },
            'string': {
                pattern: /[^\s]+(?:\s+[^\s]+)*/,
                alias: 'string',
            }
        },
    },
    'array': {
        pattern: /(?<=:\s*)\[(?:[^\[\]]|\[(?:[^\[\]]|\[(?:[^\[\]]|\[[^\[\]]*\])*\])*\])*\](?=\s*(?:\n|$))/ms,
        alias: 'language-zolo',
        lookbehind: true,
        greedy: true,
        inside: {
            'bracket': {
                pattern: /[\[\]]/,
                alias: 'bracket',
            },
            'comma': {
                pattern: /,/,
                alias: 'punctuation',
            },
            'object': {
                pattern: /\{(?:[^{}]|\{[^{}]*\})*\}/,
                alias: 'language-zolo',
                greedy: true,
                inside: {
                    'brace': {
                        pattern: /[{}]/,
                        alias: 'brace',
                    },
                    'comma': {
                        pattern: /,/,
                        alias: 'punctuation',
                    },
                    'property': {
                        pattern: /[a-zA-Z][a-zA-Z0-9_]*(?=\s*:)/,
                        alias: 'property',
                    },
                    'colon': {
                        pattern: /:/,
                        alias: 'punctuation',
                    },
                    'array': {
                        pattern: /\[(?:[^\[\]]|\[(?:[^\[\]]|\[(?:[^\[\]]|\[[^\[\]]*\])*\])*\])*\]/,
                        alias: 'language-zolo',
                        greedy: true,
                        inside: {
                            'bracket': {
                                pattern: /[\[\]]/,
                                alias: 'bracket',
                            },
                            'comma': {
                                pattern: /,/,
                                alias: 'punctuation',
                            },
                            'string': {
                                pattern: /[^\[\],\s]+(?:\s+[^\[\],\s]+)*/,
                                alias: 'string',
                            }
                        },
                    },
                    'boolean': {
                        pattern: /\b(?:true|false|True|False)\b/,
                        alias: 'boolean',
                    },
                    'null': {
                        pattern: /\bnull\b/,
                        alias: 'null',
                    },
                    'number': {
                        pattern: /(?<![a-zA-Z0-9_])-?(?:0(?!\d)|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?(?![a-zA-Z0-9_])/,
                        alias: 'number',
                    },
                    'string': {
                        pattern: /[^{}\[\],:\s]+(?:\s+[^{}\[\],:\s]+)*/,
                        alias: 'string',
                    }
                },
            },
            'nested-array': {
                pattern: /\[(?:[^\[\]]|\[(?:[^\[\]]|\[(?:[^\[\]]|\[[^\[\]]*\])*\])*\])*\]/,
                alias: 'language-zolo',
                greedy: true,
                inside: {
                    'bracket': {
                        pattern: /[\[\]]/,
                        alias: 'bracket',
                    },
                    'comma': {
                        pattern: /,/,
                        alias: 'punctuation',
                    },
                    'string': {
                        pattern: /[^\[\],\s]+(?:\s+[^\[\],\s]+)*/,
                        alias: 'string',
                    }
                },
            },
            'boolean': {
                pattern: /\b(?:true|false|True|False)\b/,
                alias: 'boolean',
            },
            'null': {
                pattern: /\bnull\b/,
                alias: 'null',
            },
            'number': {
                pattern: /(?<![a-zA-Z0-9_])-?(?:0(?!\d)|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?(?![a-zA-Z0-9_])/,
                alias: 'number',
            },
            'string': {
                pattern: /[^\[\],\s]+(?:\s+[^\[\],\s]+)*/,
                alias: 'string',
            }
        },
    },
    'object': {
        pattern: /(?<=:\s*)\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*\})*\})*\}(?=\s*(?:\n|$))/m,
        alias: 'language-zolo',
        lookbehind: true,
        greedy: true,
        inside: {
            'brace': {
                pattern: /[{}]/,
                alias: 'brace',
            },
            'comma': {
                pattern: /,/,
                alias: 'punctuation',
            },
            'property': {
                pattern: /[a-zA-Z][a-zA-Z0-9_]*(?=\s*(?:\([^)]+\))?\s*:)/,
                alias: 'property',
            },
            'type-hint': {
                pattern: /\([^)]+\)(?=\s*:)/,
                inside: {
                    'type-hint-paren': {
                        pattern: /[()]/,
                        alias: 'punctuation',
                    },
                    'type-hint-text': {
                        pattern: /[^()]+/,
                        alias: 'type',
                    }
                },
            },
            'colon': {
                pattern: /:/,
                alias: 'punctuation',
            },
            'nested-array': {
                pattern: /\[(?:[^\[\]]|\[(?:[^\[\]]|\[(?:[^\[\]]|\[[^\[\]]*\])*\])*\])*\]/,
                alias: 'language-zolo',
                greedy: true,
                inside: {
                    'bracket': {
                        pattern: /[\[\]]/,
                        alias: 'bracket',
                    },
                    'comma': {
                        pattern: /,/,
                        alias: 'punctuation',
                    },
                    'boolean': {
                        pattern: /\b(?:true|false|True|False)\b/,
                        alias: 'boolean',
                    },
                    'null': {
                        pattern: /\bnull\b/,
                        alias: 'null',
                    },
                    'number': {
                        pattern: /(?<![a-zA-Z0-9_])-?(?:0(?!\d)|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?(?![a-zA-Z0-9_])/,
                        alias: 'number',
                    },
                    'string': {
                        pattern: /[^\[\],\s]+(?:\s+[^\[\],\s]+)*/,
                        alias: 'string',
                    }
                },
            },
            'nested-object': {
                pattern: /\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*\})*\})*\}/,
                alias: 'language-zolo',
                greedy: true,
                inside: Prism.languages.zolo,
            },
            'boolean': {
                pattern: /\b(?:true|false|True|False)\b/,
                alias: 'boolean',
            },
            'null': {
                pattern: /\bnull\b/,
                alias: 'null',
            },
            'number': {
                pattern: /(?<![a-zA-Z0-9_])-?(?:0(?!\d)|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?(?![a-zA-Z0-9_])/,
                alias: 'number',
            },
            'string': {
                pattern: /[^{},:\s]+(?:\s+[^{},:\s]+)*/,
                alias: 'string',
            }
        },
    },
    'boolean': {
        pattern: /(?<=:\s+)(?:true|false|True|False)(?=\s*$)/m,
        alias: 'boolean',
        lookbehind: true,
    },
    'number': {
        pattern: /(?<=:\s+)-?(?:0(?!\d)|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?(?=\s*$)/m,
        alias: 'number',
        lookbehind: true,
    },
    'null': {
        pattern: /(?<=:\s+)null(?=\s*$)/m,
        alias: 'null',
        lookbehind: true,
    },
    'timestamp-string': {
        pattern: /(?<=:\s+)\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[^\s]*/m,
        alias: 'string',
        lookbehind: true,
    },
    'time-string': {
        pattern: /(?<=:\s+)\d{2}:\d{2}(?::\d{2})?(?=\s*$)/m,
        alias: 'string',
        lookbehind: true,
    },
    'version-string': {
        pattern: /(?<=:\s+)\d+\.\d+(?:\.\d+|\.\*)+(?=\s*$)/m,
        alias: 'string',
        lookbehind: true,
    },
    'ratio-string': {
        pattern: /(?<=:\s+)\d{1,3}:\d{1,3}(?=\s*$)/m,
        alias: 'string',
        lookbehind: true,
    },
    'string-unquoted': {
        pattern: /(?<=:\s*)\S+(?:\s+\S+)*/m,
        alias: 'string',
        lookbehind: true,
        inside: {
            'escape-sequence': {
                pattern: /\\[nrt\\\\"']|\\u[0-9A-Fa-f]{4}|\\U[0-9A-Fa-f]{4,8}/,
                alias: 'constant',
            }
        },
    },
    'colon': {
        pattern: /:/,
        alias: 'punctuation',
    }
};
